### ISSUE TITLE
How to build this?

### ISSUE THREAD

**Issue by sthibaul** [RastislavKish/nvda2speechd#3]
Hello,

It would be useful to provide step-by-step information how to build this, such as

```
$ cd src/server
$ cargo build 
$ cd ../client
$ cargo build --target x86_64-pc-windows-msvc
```

I'm notably not sure about the target that is supposed to be used. Actually on my Debian system that fails with:

```
error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-pc-windows-msvc` target may not be installed
  = help: consider downloading the target with `rustup target add x86_64-pc-windows-msvc`

error[E0463]: can't find crate for `compiler_builtins`

For more information about this error, try `rustc --explain E0463`.
error: could not compile `tinyvec_macros` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed
```

But I don't have any `rustup` tool.

Samuel

**Comment by RastislavKish** [comment]
@sthibaul thanks for filling out the issue!
Yes, that sounds like a good idea. In fact, I wanted to do so, but since I was under a time pressure at the time of the writing and didn't want to mess my PC with Windows compilers, I simply compiled the client in a Windows VM and just added a reference, since getting one via [Quickemu](https://github.com/quickemu-project/quickemu) is a very swift, fast and convenient these days.
However, it's true not all machines are suitable for VMs, and some users might not even be familiar with Windows, so a direct compilation is likely a preferred option.
I will try to write something down.

Rustup is an SDK manager of Rust, or a toolchain manager (in Rust terms), and is used to install, update and switch used Rust toolchains.
The Rust installation itself is [officially recommended](https://www.rust-lang.org/tools/install) to be done via Rustup.

There are various toolchains for various compilers and platforms. The MSVC-one uses the Microsoft's MSVC compiler, and thus requires it to be installed on the Windows machine (via VisualStudio, for example).

**Comment by RastislavKish** [comment]
@sthibaul I have added a compilation script, that should significantly ease the full on-Linux building.
I updated the readme with new compilation instructions, as well as a more detailed listing of dependencies and the way to install them.
Could you check now whether it works properly and contains all the required information?

**Comment by sthibaul** [comment]
This looks good, thanks!
